-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 13:18:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movie_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_app` DEFAULT CHARACTER SET utf8mb4 ;
USE `movie_app` ;

-- -----------------------------------------------------
-- Table `movie_app`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_app`.`categories` ;

CREATE TABLE IF NOT EXISTS `movie_app`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movie_app`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_app`.`movies` ;

CREATE TABLE IF NOT EXISTS `movie_app`.`movies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` INT(11) NULL DEFAULT NULL,
  `poster_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movie_app`.`movie_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_app`.`movie_categories` ;

CREATE TABLE IF NOT EXISTS `movie_app`.`movie_categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `movie_id` INT(11) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `movie_id` (`movie_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `movie_categories_ibfk_1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_app`.`movies` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `movie_categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `movie_app`.`categories` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movie_app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_app`.`users` ;

CREATE TABLE IF NOT EXISTS `movie_app`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movie_app`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_app`.`reviews` ;

CREATE TABLE IF NOT EXISTS `movie_app`.`reviews` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `movie_id` INT(11) NULL DEFAULT NULL,
  `rating` INT(11) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `movie_id` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `movie_app`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_app`.`movies` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
